version: "3"
services:
  database:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=site
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - db-data:/data/db
    ports:
      - '27017-27019:27017-27019'
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.10
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
  graylog:
    image: graylog/graylog:3.3
    environment:
      - GRAYLOG_PASSWORD_SECRET=lokijuhygtrwghth
      - GRAYLOG_ROOT_PASSWORD=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
      - "GRAYLOG_MONGODB_URI=mongodb://root:root@database:27017/graylog?authSource=admin"
    volumes:
      - graylog_data:/usr/share/graylog/data
    depends_on:
      - elasticsearch
      - database
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
volumes:
  db-data:
  graylog_data:
  es_data:
